<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio touring module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Touring\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Tours, the tiers they are sold in, and their stays.
 */
final class Version20261006000600 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'touring_tour, touring_tour_day';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE touring_tour (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(120) NOT NULL, summary TEXT NOT NULL, group_min INT NOT NULL, group_max INT NOT NULL, included JSON NOT NULL, excluded JSON NOT NULL, tiers JSON NOT NULL, status VARCHAR(16) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A18A7630D17F50A6 ON touring_tour (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A18A76305E237E06 ON touring_tour (name)');
        $this->addSql('CREATE TABLE touring_tour_day (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, number INT NOT NULL, title VARCHAR(120) NOT NULL, destinations JSON NOT NULL, nights INT NOT NULL, stays JSON NOT NULL, activities VARCHAR(240) NOT NULL, meals JSON NOT NULL, description TEXT NOT NULL, distance_km INT DEFAULT NULL, drive_hours NUMERIC(3, 1) DEFAULT NULL, tour_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_68213F96D17F50A6 ON touring_tour_day (uuid)');
        $this->addSql('CREATE INDEX IDX_68213F9615ED8D43 ON touring_tour_day (tour_id)');
        $this->addSql('ALTER TABLE touring_tour_day ADD CONSTRAINT FK_68213F9615ED8D43 FOREIGN KEY (tour_id) REFERENCES touring_tour (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE touring_tour_day');
        $this->addSql('DROP TABLE touring_tour');
    }
}
