<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio touring module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Touring\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Tour seasons, the same every year, and each tour's rate card: a price per
 * person by season, tier and group size, in the tour's currency.
 */
final class Version20261007000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'touring_season, touring_rate, touring_tour.price_currency and brackets';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE touring_season (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(60) NOT NULL, tone INT NOT NULL, periods JSON NOT NULL, for_the_rest BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E69AE85ED17F50A6 ON touring_season (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E69AE85E5E237E06 ON touring_season (name)');
        $this->addSql('CREATE TABLE touring_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tier INT NOT NULL, min_people INT NOT NULL, max_people INT NOT NULL, amount NUMERIC(12, 2) NOT NULL, tour_id INT NOT NULL, season_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_14B7B06015ED8D43 ON touring_rate (tour_id)');
        $this->addSql('CREATE INDEX IDX_14B7B0604EC001D1 ON touring_rate (season_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_14B7B06015ED8D434EC001D1249E978ABE7B301B ON touring_rate (tour_id, season_id, tier, min_people)');
        $this->addSql('ALTER TABLE touring_rate ADD CONSTRAINT FK_14B7B06015ED8D43 FOREIGN KEY (tour_id) REFERENCES touring_tour (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE touring_rate ADD CONSTRAINT FK_14B7B0604EC001D1 FOREIGN KEY (season_id) REFERENCES touring_season (id) ON DELETE CASCADE');
        $this->addSql("ALTER TABLE touring_tour ADD price_currency VARCHAR(3) DEFAULT '' NOT NULL");
        $this->addSql("ALTER TABLE touring_tour ADD brackets JSON DEFAULT '[]' NOT NULL");
        $this->addSql('ALTER TABLE touring_tour ALTER price_currency DROP DEFAULT');
        $this->addSql('ALTER TABLE touring_tour ALTER brackets DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE touring_rate');
        $this->addSql('DROP TABLE touring_season');
        $this->addSql('ALTER TABLE touring_tour DROP price_currency, DROP brackets');
    }
}
