<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio touring module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Touring\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Departures, set days a tour leaves sold by the seat, and the bookings on them.
 */
final class Version20261007000500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'touring_departure, touring_booking.departure_id';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE touring_departure (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, status VARCHAR(16) NOT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancellation_reason VARCHAR(200) DEFAULT NULL, start DATE NOT NULL, tier SMALLINT NOT NULL, seats SMALLINT NOT NULL, runs_with SMALLINT NOT NULL, seat INT NOT NULL, tour_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D370272D17F50A6 ON touring_departure (uuid)');
        $this->addSql('CREATE INDEX IDX_8D37027215ED8D43 ON touring_departure (tour_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D37027215ED8D439F79558F ON touring_departure (tour_id, start)');
        $this->addSql('ALTER TABLE touring_departure ADD CONSTRAINT FK_8D37027215ED8D43 FOREIGN KEY (tour_id) REFERENCES touring_tour (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE touring_booking ADD departure_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_C3C3F4D27704ED06 ON touring_booking (departure_id)');
        $this->addSql('ALTER TABLE touring_booking ADD CONSTRAINT FK_C3C3F4D27704ED06 FOREIGN KEY (departure_id) REFERENCES touring_departure (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE touring_booking DROP CONSTRAINT FK_C3C3F4D27704ED06');
        $this->addSql('ALTER TABLE touring_booking DROP departure_id');
        $this->addSql('DROP TABLE touring_departure');
    }
}
