<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio touring module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Touring\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Tour bookings, each keeping the price it was sold at.
 */
final class Version20261007000200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'touring_booking';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE touring_booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, reference VARCHAR(16) NOT NULL, guest VARCHAR(120) NOT NULL, booked_by VARCHAR(120) DEFAULT NULL, their_reference VARCHAR(60) DEFAULT NULL, start DATE NOT NULL, adults SMALLINT NOT NULL, children SMALLINT NOT NULL, residency VARCHAR(16) NOT NULL, tier SMALLINT NOT NULL, tier_name VARCHAR(40) NOT NULL, season_name VARCHAR(60) NOT NULL, size VARCHAR(20) NOT NULL, currency VARCHAR(3) NOT NULL, each INT NOT NULL, gross INT NOT NULL, total INT NOT NULL, partner_id VARCHAR(36) DEFAULT NULL, discount NUMERIC(5, 2) NOT NULL, credit_days INT NOT NULL, status VARCHAR(16) NOT NULL, held_until DATE DEFAULT NULL, notes TEXT DEFAULT NULL, made_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancellation_reason VARCHAR(200) DEFAULT NULL, tour_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C3C3F4D2D17F50A6 ON touring_booking (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C3C3F4D2AEA34913 ON touring_booking (reference)');
        $this->addSql('CREATE INDEX IDX_C3C3F4D215ED8D43 ON touring_booking (tour_id)');
        $this->addSql('ALTER TABLE touring_booking ADD CONSTRAINT FK_C3C3F4D215ED8D43 FOREIGN KEY (tour_id) REFERENCES touring_tour (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE touring_booking');
    }
}
