<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio touring module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Touring\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Cancellation: the tours' terms, a tour's own, and the tiers and charge a
 * booking keeps.
 */
final class Version20261007000600 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'touring_terms, touring_tour.cancellation, touring_booking.cancellation_tiers and cancellation_charge';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE touring_terms (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cancellation JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE touring_tour ADD cancellation JSON DEFAULT NULL');
        $this->addSql("ALTER TABLE touring_booking ADD cancellation_tiers JSON DEFAULT '[]' NOT NULL");
        $this->addSql('ALTER TABLE touring_booking ALTER cancellation_tiers DROP DEFAULT');
        $this->addSql('ALTER TABLE touring_booking ADD cancellation_charge INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE touring_terms');
        $this->addSql('ALTER TABLE touring_tour DROP cancellation');
        $this->addSql('ALTER TABLE touring_booking DROP cancellation_tiers, DROP cancellation_charge');
    }
}
